#!/bin/bash
#PBS -j oe
#PBS -l nodes=1:ppn=1
#PBS -l walltime=240:00:00
#PBS -l cput=240:00:00
##PBS -m abe
#PBS -M malramsay64+silica@gmail.com


source /etc/profile.d/modules.sh
module load intel openmpi-intel

cd $PREFIX/$mol
cat ${PBS_NODEFILE} > nodes.txt

echo "Begin" > out.log
echo $mol dist: $dist rad: $rad theta: $theta >> out.log

if [ ! -z $dist ] ; then
    echo $mol >> out.log
    echo "$BIN_PATH/wallpaper 1 dimer all $dist $rad" >> out.log
    $BIN_PATH/wallpaper 1 dimer all $dist $rad >> out.log
else
    if [ ! -z $theta ]; then
        echo $mol >> out.log
        echo "$BIN_PATH/wallpaper 1 trimer all $rad $theta" >> out.log
        $BIN_PATH/wallpaper 1 trimer all $rad $theta >> out.log
    fi
fi

echo "Finished" >> out.log
