include vars.mak

shape := $(call p_shape, $(mol))
radius := $(call p_rad, $(mol))
dist := $(call p_dist, $(mol))
theta := $(call p_theta, $(mol))
bound := $(call p_bound, $(mol))

# Temp range for each d
ifdef temp_$(dist)
	temp := $(temp_$(dist))
endif

save1 := $(addsuffix $(subst $(space),-,-$(strip $(radius) $(dist) $(theta) $(bound))), $(temp)) 
save := $(addprefix $(strip $(shape))-, $(save1)) 

dirs:=$(addprefix $(PREFIX)/,$(save))
last_t:=$(word 1, $(temp))

OPTIONS = --no-print-directory $(if $(filter $(MAKECMDGOALS), $(PRE)), -j 1)

export

$(MAKECMDGOALS): $(save)

$(save): always | $(dirs)
	$(foreach t, $(temp), $(if $(filter $(call t_temp, $@), $t), $(eval prev_t=$(last_t)), $(eval last_t=$t)))
ifeq ($(SYS_NAME), silica)
ifeq ($(t_dep), false)
	@qsub -N $@ -o pbsout/$@.out single.pbs -vmol=$@,prev_t=$(prev_t),target=$(MAKECMDGOALS),prefix=$(PREFIX)/$@,my_dir=$(my_dir)
else
	@$(MAKE) $(OPTIONS) -C $(PREFIX)/$@ -f $(my_dir)/$(GOAL) $(MAKECMDGOALS) mol=$@ prev_t=$(prev_t)
endif
else
	@$(MAKE) $(OPTIONS) -C $(PREFIX)/$@ -f $(my_dir)/$(GOAL) $(MAKECMDGOALS) mol=$@ prev_t=$(prev_t)
endif

$(dirs):
	@-mkdir $@

.PHONY: always
always:
