
include settings
include config

mol := $(shape)
mol := $(filter Snowman%, $(mol))
# Radii
mol := $(if $(radius), $(foreach rad, $(radius), $(addsuffix -$(rad), $(mol))), $(mol))
# Distance
mol := $(if $(dist), $(foreach rad, $(dist), $(addsuffix -$(rad), $(mol))), $(mol))
# Calc Distance
mol := $(foreach m, $(mol), $(m:$(call p_dist, $m)=$(call comp_dist, $(call p_dist, $m), $(call p_rad, $m))))

VPATH:=.:$(BIN_PATH):isopointal

MODULES:=shapes.o fluke.o groups.o wallpaper.o

all: wallpaper

iso: $(mol)

Snowman-%: wallpaper | $(PREFIX)/Snowman-%
	cd $(PREFIX)/$@; $(BIN_PATH)/wallpaper 1 anyu all $(call p_dist, $@) $(call p_rad, $@) > out.log

$(PREFIX)/%:
	mkdir -p $@

wallpaper: $(MODULES)
	$(CC) -o $(BIN_PATH)/$@ $(addprefix $(BIN_PATH)/, $(MODULES)) $(CFLAGS) $(LDFLAGS)

%.o: %.c | $(BIN_PATH)
	$(CC) $(CFLAGS) -c $< -o $(BIN_PATH)/$@

clean:
	rm $(BIN_PATH)/*
